version: '3'
services:
  caddy:
    image: caddy:alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
    pull_policy: always
    restart: always
  keycloak:
    image: "ghcr.io/pccsuite/pcckeycloak"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD
      - KC_DB=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
    depends_on:
      - postgres
    pull_policy: always
    restart: always
  postgres:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=${KC_DB_PASSWORD}
    volumes:
      - ${KEYCLOAK_DATADIR}:/var/lib/postgresql/data
    pull_policy: always
    restart: always